/**
 * Reconciliation prompt template (S2-03).
 *
 * Merges UI-observed Gherkin scenarios with code-extracted business rules into
 * enriched, authoritative Gherkin. Gaps (rules with no UI evidence) and
 * conflicts (UI behaviour contradicting a rule) are surfaced explicitly.
 *
 * Output schema is compatible with {@link LlmService.completeJson}.
 */

import { JsonSchema, ObjectSchema } from '../llm.service';

// ─── Input type ─────────────────────────────────────────────────────────────────

/** A Gherkin step as previously generated by the gherkin-generation template. */
export interface ReconciliationStep {
  readonly keyword: string;
  readonly text: string;
}

/** A Gherkin scenario from the UI observation phase. */
export interface ObservedScenario {
  readonly title: string;
  readonly steps: readonly ReconciliationStep[];
  readonly tags?: readonly string[];
}

/** A business rule extracted from the code-analysis phase. */
export interface CodeRule {
  readonly ruleId: string;
  readonly statement: string;
  readonly severity: string;
  readonly category?: string;
}

/** Inputs required to render the reconciliation prompt. */
export interface ReconciliationInput {
  /** Feature name shared across both sources. */
  readonly featureName: string;
  /** Gherkin scenarios from Phase 1 (UI exploration). */
  readonly observedScenarios: readonly ObservedScenario[];
  /** Business rules extracted from Phase 2 (code analysis). */
  readonly codeRules: readonly CodeRule[];
  /** Optional reconciliation notes or user-supplied hints. */
  readonly notes?: string;
}

// ─── Output type ────────────────────────────────────────────────────────────────

/** How the reconciliation resolved a particular scenario or rule. */
export type ReconciliationStatus = 'matched' | 'gap' | 'conflict' | 'new';

/** An enriched Gherkin step. */
export interface EnrichedStep {
  readonly keyword: string;
  readonly text: string;
  /** Optional ruleId(s) that informed or verified this step. */
  readonly supportedBy?: readonly string[];
}

/** An enriched Gherkin scenario produced by reconciliation. */
export interface EnrichedScenario {
  readonly title: string;
  readonly steps: readonly EnrichedStep[];
  readonly tags?: readonly string[];
  /** Reconciliation status of this scenario. */
  readonly status: ReconciliationStatus;
  /** Human-readable explanation of how this scenario was resolved. */
  readonly rationale: string;
}

/** A gap: a business rule with no corresponding UI scenario. */
export interface RuleGap {
  readonly ruleId: string;
  readonly statement: string;
  /** Recommended Gherkin step text to cover this gap (for human review). */
  readonly suggestedStep: string;
}

/** A conflict: UI behaviour that contradicts a business rule. */
export interface RuleConflict {
  readonly ruleId: string;
  readonly scenarioTitle: string;
  readonly description: string;
}

/** Structured output shape returned by the reconciliation LLM call. */
export interface ReconciliationOutput {
  readonly featureName: string;
  /** Enriched, authoritative Gherkin scenarios. */
  readonly scenarios: readonly EnrichedScenario[];
  /** Rules present in code but with no corresponding UI scenario. */
  readonly gaps: readonly RuleGap[];
  /** Contradictions between UI behaviour and code rules. */
  readonly conflicts: readonly RuleConflict[];
  /** Overall confidence level (0–100). */
  readonly confidenceScore: number;
}

// ─── Template metadata ──────────────────────────────────────────────────────────

export const RECONCILIATION_TEMPLATE_ID = 'reconciliation' as const;
export const RECONCILIATION_TEMPLATE_VERSION = '1.0.0' as const;

// ─── Output schema ──────────────────────────────────────────────────────────────

/** Runtime JSON schema for {@link ReconciliationOutput}, for use with `completeJson`. */
export const RECONCILIATION_OUTPUT_SCHEMA: ObjectSchema = {
  type: 'object',
  properties: {
    featureName: { type: 'string' },
    scenarios: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          steps: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                keyword: { type: 'string' },
                text: { type: 'string' },
                supportedBy: {
                  type: 'array',
                  items: { type: 'string' },
                },
              },
              required: ['keyword', 'text'],
              additionalProperties: false,
            },
          },
          tags: {
            type: 'array',
            items: { type: 'string' },
          },
          status: {
            type: 'string',
            enum: ['matched', 'gap', 'conflict', 'new'],
          },
          rationale: { type: 'string' },
        },
        required: ['title', 'steps', 'status', 'rationale'],
        additionalProperties: false,
      },
    },
    gaps: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          ruleId: { type: 'string' },
          statement: { type: 'string' },
          suggestedStep: { type: 'string' },
        },
        required: ['ruleId', 'statement', 'suggestedStep'],
        additionalProperties: false,
      },
    },
    conflicts: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          ruleId: { type: 'string' },
          scenarioTitle: { type: 'string' },
          description: { type: 'string' },
        },
        required: ['ruleId', 'scenarioTitle', 'description'],
        additionalProperties: false,
      },
    },
    confidenceScore: { type: 'number' },
  },
  required: ['featureName', 'scenarios', 'gaps', 'conflicts', 'confidenceScore'],
  additionalProperties: false,
} satisfies JsonSchema;

// ─── Render function ─────────────────────────────────────────────────────────────

/**
 * Render the reconciliation prompt string from typed inputs.
 *
 * @param input Typed inputs for this reconciliation request.
 * @returns A prompt string ready to pass to {@link LlmService.completeJson}.
 */
export function renderReconciliationPrompt(input: ReconciliationInput): string {
  const { featureName, observedScenarios, codeRules, notes } = input;

  const scenariosJson = JSON.stringify(observedScenarios, null, 2);
  const rulesJson = JSON.stringify(codeRules, null, 2);
  const notesSection = notes ? `## Reconciliation notes\n${notes}\n\n` : '';

  return `You are a Senior Business Analyst reconciling two sources of truth about \
the feature "${featureName}":
1. **UI observations** — Gherkin scenarios captured by automated Playwright exploration.
2. **Code rules** — Business rules extracted from the application source code.

Your task is to produce enriched, authoritative Gherkin that represents BOTH sources \
faithfully, surface any gaps (rules with no UI evidence) and conflicts (UI behaviour \
contradicting a code rule), and score your overall confidence in the reconciliation.

${notesSection}## UI-observed Gherkin scenarios
\`\`\`json
${scenariosJson}
\`\`\`

## Code-extracted business rules
\`\`\`json
${rulesJson}
\`\`\`

## Reconciliation instructions
1. For each UI scenario, find code rules that support, extend, or contradict it.
   - **matched**: scenario aligns with at least one rule — enrich its steps with \
the rule IDs in "supportedBy".
   - **conflict**: scenario contradicts a rule — flag it and document the conflict.
   - **new**: scenario has no related rule but is valid UI behaviour — keep it, \
status = "new".
2. For each code rule with NO matching UI scenario, add an entry to "gaps" with a \
suggested Gherkin step the BA should write.
3. All enriched scenarios MUST remain valid Gherkin (Given/When/Then structure).
4. The "confidenceScore" is 0–100: 100 = all scenarios fully matched by rules, \
0 = nothing matches.
5. Be conservative: if unsure whether a rule matches a scenario, prefer "new" over \
"matched".

Respond ONLY with a JSON object — no markdown fences, no prose:

{
  "featureName": "<name>",
  "scenarios": [
    {
      "title": "<title>",
      "tags": ["@tag"],
      "status": "matched|gap|conflict|new",
      "rationale": "<why this status>",
      "steps": [
        { "keyword": "Given", "text": "<context>", "supportedBy": ["ruleId"] },
        { "keyword": "When",  "text": "<action>" },
        { "keyword": "Then",  "text": "<outcome>" }
      ]
    }
  ],
  "gaps": [
    { "ruleId": "<id>", "statement": "<rule>", "suggestedStep": "<Gherkin step text>" }
  ],
  "conflicts": [
    { "ruleId": "<id>", "scenarioTitle": "<title>", "description": "<what conflicts>" }
  ],
  "confidenceScore": 85
}`;
}
