import { GherkinDoc, GherkinFeature, GherkinScenario, GherkinStep } from '@baia/shared';

function escapeXml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderSteps(steps: GherkinStep[]): string {
  return steps.map((s) => `${s.keyword} ${s.text}`).join('\n');
}

function renderScenario(scenario: GherkinScenario): string {
  const parts: string[] = [];

  parts.push(`<h3>${escapeXml(scenario.name)}</h3>`);

  if (scenario.conflictNote) {
    parts.push(
      `<ac:structured-macro ac:name="warning" ac:schema-version="1">` +
        `<ac:rich-text-body><p>${escapeXml(scenario.conflictNote)}</p></ac:rich-text-body>` +
        `</ac:structured-macro>`
    );
  }

  const stepsText = renderSteps(scenario.steps);
  parts.push(
    `<ac:structured-macro ac:name="code" ac:schema-version="1">` +
      `<ac:parameter ac:name="language">gherkin</ac:parameter>` +
      `<ac:plain-text-body><![CDATA[${stepsText}]]></ac:plain-text-body>` +
      `</ac:structured-macro>`
  );

  return parts.join('\n');
}

function renderFeature(feature: GherkinFeature): string {
  const parts: string[] = [];

  parts.push(`<h2>${escapeXml(feature.name)}</h2>`);

  if (feature.description) {
    parts.push(`<p>${escapeXml(feature.description)}</p>`);
  }

  for (const scenario of feature.scenarios) {
    parts.push(renderScenario(scenario));
  }

  return parts.join('\n');
}

/**
 * Derive the Confluence page title from a GherkinDoc's first feature name.
 * Falls back to generic title if the doc has no features.
 */
export function gherkinDocTitle(doc: GherkinDoc): string {
  const name = doc.features[0]?.name;
  return name ? `BAIA: ${name}` : 'BAIA: Generated Documentation';
}

/**
 * Convert a GherkinDoc into Confluence storage-format markup.
 *
 * Features map to <h2> sections, scenarios to <h3> sub-sections with a
 * Gherkin code macro. Conflict notes render as warning panels. All
 * user-supplied text is XML-escaped.
 */
export function gherkinDocToConfluenceStorage(doc: GherkinDoc): string {
  const sections: string[] = [];

  sections.push(`<p><em>Generated by BAIA on ${escapeXml(doc.generatedAt.toISOString())}</em></p>`);

  for (const feature of doc.features) {
    sections.push(renderFeature(feature));
  }

  return sections.join('\n');
}
