import { GherkinDoc, GherkinFeature, GherkinScenario, GherkinStep } from '@baia/shared';
import AdmZip from 'adm-zip';

/**
 * Converts a string name to a safe, URL-friendly kebab-case filename.
 */
export function toSafeFilename(name: string): string {
  const safe = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
  return safe || 'unnamed-feature';
}

/**
 * Renders a single Gherkin step.
 */
export function renderGherkinStep(step: GherkinStep): string {
  return `${step.keyword} ${step.text}`;
}

/**
 * Renders a collection of scenarios in plain Gherkin format.
 */
export function renderRawGherkinScenarios(scenarios: GherkinScenario[]): string {
  const parts: string[] = [];
  for (const s of scenarios) {
    parts.push(`  Scenario: ${s.name}`);
    for (const step of s.steps) {
      parts.push(`    ${renderGherkinStep(step)}`);
    }
    parts.push(''); // spacing between scenarios
  }
  return parts.join('\n');
}

/**
 * Converts a GherkinFeature into the standard, plain .feature text format.
 */
export function gherkinFeatureToText(feature: GherkinFeature): string {
  const parts: string[] = [];
  parts.push(`Feature: ${feature.name}`);
  if (feature.description) {
    parts.push(`  ${feature.description}`);
  }
  parts.push(''); // spacer

  parts.push(renderRawGherkinScenarios(feature.scenarios));
  return parts.join('\n').trim() + '\n';
}

/**
 * Converts a GherkinDoc into a single consolidated raw Gherkin text.
 */
export function gherkinDocToText(doc: GherkinDoc): string {
  return doc.features.map(gherkinFeatureToText).join('\n\n');
}

/**
 * Converts a GherkinFeature into an OKF-compliant Concept Markdown document.
 */
export function gherkinFeatureToOkfMarkdown(
  feature: GherkinFeature,
  doc: GherkinDoc,
  targetUrl: string
): string {
  const yamlFrontmatter = [
    '---',
    'type: Feature',
    `title: ${JSON.stringify(feature.name)}`,
    `description: ${JSON.stringify(feature.description || '')}`,
    `resource: ${JSON.stringify(targetUrl)}`,
    `timestamp: ${JSON.stringify(doc.generatedAt instanceof Date ? doc.generatedAt.toISOString() : new Date(doc.generatedAt).toISOString())}`,
    '---',
  ].join('\n');

  const mdBody: string[] = [];
  mdBody.push(`# ${feature.name}`);
  mdBody.push('');
  if (feature.description) {
    mdBody.push(feature.description);
    mdBody.push('');
  }

  mdBody.push('## Scenarios');
  mdBody.push('');

  for (const s of feature.scenarios) {
    mdBody.push(`### ${s.name}`);
    mdBody.push('');

    if (s.conflictNote) {
      mdBody.push(`> [!WARNING]`);
      mdBody.push(`> **Reconciliation Warning**: ${s.conflictNote}`);
      mdBody.push('');
    }

    mdBody.push('```gherkin');
    for (const step of s.steps) {
      mdBody.push(renderGherkinStep(step));
    }
    mdBody.push('```');
    mdBody.push('');
  }

  return `${yamlFrontmatter}\n\n${mdBody.join('\n').trim()}\n`;
}

/**
 * Creates an OKF index.md listing all the features in the bundle.
 */
export function generateOkfIndex(doc: GherkinDoc): string {
  const timestamp =
    doc.generatedAt instanceof Date
      ? doc.generatedAt.toISOString()
      : new Date(doc.generatedAt).toISOString();
  const yamlFrontmatter = [
    '---',
    'type: System',
    'title: BAIA Generated Documentation',
    `timestamp: ${JSON.stringify(timestamp)}`,
    '---',
  ].join('\n');

  const mdBody: string[] = [];
  mdBody.push('# BAIA Generated Documentation');
  mdBody.push('');
  mdBody.push(`Generated by BAIA on ${timestamp}.`);
  mdBody.push('');
  mdBody.push('## Features');
  mdBody.push('');

  for (const feature of doc.features) {
    const filename = toSafeFilename(feature.name);
    mdBody.push(
      `- **[${feature.name}](features/${filename}.md)** (Gherkin source: [${filename}.feature](features/${filename}.feature))`
    );
  }

  return `${yamlFrontmatter}\n\n${mdBody.join('\n').trim()}\n`;
}

/**
 * Bundles the GherkinDoc into a ZIP archive buffer containing the index, OKF Markdown, and raw `.feature` files.
 */
export function gherkinDocToOkfZip(doc: GherkinDoc, targetUrl: string): Buffer {
  const zip = new AdmZip();

  // Add index.md
  const indexContent = generateOkfIndex(doc);
  zip.addFile('index.md', Buffer.from(indexContent, 'utf-8'));

  // Add features
  for (const feature of doc.features) {
    const filename = toSafeFilename(feature.name);

    // 1. OKF Concept Markdown file
    const okfMd = gherkinFeatureToOkfMarkdown(feature, doc, targetUrl);
    zip.addFile(`features/${filename}.md`, Buffer.from(okfMd, 'utf-8'));

    // 2. Raw Gherkin feature file
    const rawGherkin = gherkinFeatureToText(feature);
    zip.addFile(`features/${filename}.feature`, Buffer.from(rawGherkin, 'utf-8'));
  }

  return zip.toBuffer();
}
